### PR TITLE
[WIP] Remove FOSUserBundle dependency

### LINKED ISSUE #1112: Remove FOSUserBundle inheritance
## Feature Request

This bundle is dead: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2874#issuecomment-462644756

There are some threads that were asking for new versions:
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2927 
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2917 
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2874

So we should remove the coupling to this bundle and fork/implement some of the basic functions here.

### PR DESCRIPTION
**Pull request by grimabe**
## Subject
This PR is a **WORK IN PROGRESS**. See Todo for missing changes.
Based on #1112 The lack of maintenance of FOSUserBundle will impact SonataUserBundle and this dependency must be removed.

Removing this bundle will obviously imply breaking changes due to existing : 
- FOSUserBundle configuration
- security configuration (Encoder, User provider)
- collection/table names
- forms (login, reset..)
- overriden templates
- what else ?

Looking at the impact this PR should be part of a Major Release (5.x ?)

Closes #1112 

When I looked at all the dependencies on FOSUserBundle and the coupling behind it I went with : 
1. copying all files from FOS to Sonata
2. migrating namespace and class name

in order to make all tests pass.

The rest is in the Todo =>

## Changelog

```markdown
### Added

- Migrated FOSUserBundle files into SonataUserBundle

### Changed

- Replaced FOS namespaces with Sonata

```

 ## To do
- [ ] Define the scope/list of features part of FOSUserBundle that should be kept in Sonata
- [ ] Apply changes based on previous definition
- [ ] Import required FOSUserBundle Configuration into SonataUserBundle
- [ ] Update the documentation
- [ ] Add an upgrade note

I am not used to this kind of refactoring so there might be total different opinions or different approaches. I am open to suggestion :-)

### CODE REVIEW

**Comment by core23** [comment]
Great to see some progress 🚀

Maybe it would help if you just port the necessary stuff (base user classes) and later all optional stuff (frontend controllers, reg forms, ...).

This will speed up the programm and make the review faster for us.

**Comment by Hanmac** [comment]
Question about the namespace, should the Files use "FOS*" like they currently did or shouldn't they be merged into non "FOS*" variants?

Or is that not a good idea ? ( like for someone who wants to use FOSUser instead as SonataUser as Model?)

**Comment by core23** [comment]
> Question about the namespace, should the Files use "FOS*" like they currently did or shouldn't they be merged into non "FOS*" variants?
> 

We should not use FOS prefixes anywhere, because we are not FOS

**Comment by Hanmac** [comment]
While maybe merging old FOSUser with SonataUser, (i don't know if that is good idea)

would it be nice to make the Fields of the SonataUser Configurable?
Like if you disable "social" in the config it doesn't appear in the database or in the admin?

**Comment by core23** [comment]
> would it be nice to make the Fields of the SonataUser Configurable?
> Like if you disable "social" in the config it doesn't appear in the database or in the admin?

This is not the goal of this task. This is just about porting stuff to sonata. Removing optional things from sonata is a different topic.

**Comment by core23** [comment]
When looking at https://github.com/sonata-project/ecommerce/pull/627, we could reduce this bundle to simple user management (login, admin) and could create a new **ProfileBundle** which adds a registration and profile editing in the frontend.

WDYT @grimabe @sonata-project/contributors

**Comment by wbloszyk** [comment]
ProfileBundle is tools to easy create page with global profile menu and page content. (copy of SonataUserBundle profile part). You can set menu record by bundle configuration. It can override other profile (like fos user, Sonata User < 4.x) or use them profile by set profile templete. It should not have any user form or Entity. 

Tomorrow i will check how we can reduce UserBundle and what we can add to ProfileBundle. 

@core23 Mybe ProfileBundle should be seperate Bundle, not ecommerce part?

**Comment by core23** [comment]
> Tomorrow i will check how we can reduce UserBundle and what we can add to ProfileBundle.

Yeah 🚀 
 
> @core23 Mybe ProfileBundle should be seperate Bundle, not ecommerce part?

Some parts can be moved to a new repo. Some parts must stay at the ecommerce repo, e.g. order history, etc.

**Comment by wbloszyk** [comment]
FOSUserBundle is not deprecated. It is not promote by [symfony.com](https://symfony.com/). It look like FOSUserBundle is little forgotten by fos team, but they update others bundle. 
Look at [#2947 ](https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2947) !!!

@core23 
One big question is SonataUserBundle should be full user bundle fuctionality or only user feature bundle?
 
For me:
- SonataUserBundle should be only for integrate user to admin with some feature
- FosUserBundle dependency should be remove
- ~~SonataUserBundle should Integrates the FOS/UserBundle~~
SonataUserBundle should Integrates the Symfony\Component\Security\Core\User\UserInterface 
in the Sonata Admin Project and adds some features

**Comment by core23** [comment]
> FOSUserBundle is not deprecated. It is not promote by [symfony.com](https://symfony.com/). It look like FOSUserBundle is little forgotten by fos team, but they update others bundle.
> Look at [#2947 ](https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2947)

Wow, there's something happening. When you look at old issues, there were no responses for a new minor or even a patch release.

Regardless on the v3 roadmap from the FOS team, I woud still prefer a removal of the FOS bundle and provide only a thin layer for user management.

**Comment by wbloszyk** [comment]
Like i wrote :)

Work to do:
- [ ] merge Entity/Document/Model and replace it in all use section
- [ ] replace FOSUserBundle interface by SonataUserBundle interface (copy it)
- [ ] update service extended by fos class/service
  - developer must create service based on ~~FOSInterface~~ SonataInterface
  - add it to SonataUserBundle configuration (for example UserManager)
  - sonata decorate them to own UserManager
  - this allow integrate all Users system based on UserInterface (also keep FOSUser as suggest)
- [ ] update test

**Comment by wbloszyk** [comment]
@grimabe are u work on it?

**Comment by core23** [comment]
> @grimabe are u work on it?

I'm working on a different approach this weekend. I am doing a hard fork of the fos bundle and try to bridge the old fos classes. I hope this works so I can release it in the next days.

**Comment by grimabe** [comment]
@wbloszyk @core23 I am not working on it. I did not have much time lately to focus on this issue. So yes @core23 feel free to have a look.

**Comment by wbloszyk** [comment]
>I'm working on a different approach this weekend. I am doing a hard fork of the fos bundle and try to >bridge the old fos classes. I hope this works so I can release it in the next days.

@core23 OK. My idea is something like  traits + interface / [doctrine mapping interface](https://symfony.com/doc/current/doctrine/resolve_target_entity.html)
Also profile part should be add like in [ecommerce#634](https://github.com/sonata-project/ecommerce/pull/634) and block: sonata.user.block.account 

I will back in Thursday. Then i can help.

**Comment by haivala** [comment]
What is the situation with this?

**Comment by john-dufrene-dev** [comment]
Non news about this ?

**Comment by jordisala1991** [comment]
Do you want to help with it @john-dufrene-dev ?

IMO this should be our priority after fix on Rest api, nelmio and release of AdminBundle 4 maybe... because this will go on next major. wdyt @sonata-project/contributors ?

**Comment by john-dufrene-dev** [comment]
@jordisala1991 For sure I could work on it, but it's not better in first to adapt this package with this best approch for user [https://github.com/nucleos/NucleosUserAdminBundle](url) and [,](https://github.com/nucleos/NucleosUserBundle) this packages do lot's of work and could be adapt for sonataUserBundle :
- It does not provide any advanced features like profile management or registration
- Swift mailer was dropped in favor of symfony mailer
- Couch DB support was removed
- Only symfony 4.4 / 5.x support
- There are only two optional dependencies: doctrine/orm and doctrine/mongodb-odm
package of @core23

**Comment by wbloszyk** [comment]
IMHO 

> @jordisala1991 For sure I could work on it, but it's not better in first to adapt this package with this best approch for user [https://github.com/nucleos/NucleosUserAdminBundle](url) and [(https://github.com/nucleos/NucleosUserBundle)](url) this packages do lot's of work and could be adapt for sonataUserBundle :
> 
> * It does not provide any advanced features like profile management or registration
> * Swift mailer was dropped in favor of symfony mailer
> * Couch DB support was removed
> * Only symfony 4.4 / 5.x support
> * There are only two optional dependencies: doctrine/orm and doctrine/mongodb-odm
> 
> This is a package of @core23

IMHO we should not adapt any `user-bundle` from now. Better option will be extends Symfony `AdvancedUserInterface` and allow people adapt own systems. It mean we should provide User only for Admin firewall.

**Comment by VincentLanglet** [comment]
> Do you want to help with it @john-dufrene-dev ?
> 
> IMO this should be our priority after fix on Rest api, nelmio and release of AdminBundle 4 maybe... because this will go on next major. wdyt @sonata-project/contributors ?

If someone wants to work on this, it's great.
But I would say that our first priority should be indeed AdminBundle 4 and storage bundle 4, with Symfony 5 support.
This will allow a lot of user to use Symfony 5.

Then we say every other bundle one by one to get a Symfony 5 support and be Sonata4 compatible.
FosUserBundle doesn't support Symfony 5, so it will be of course a priority.

**Comment by grimabe** [comment]
I am closing the PR as the changes are not relevant.
Maybe it is best to discuss it in an issue.
I'll be glad to give a hand if there are some parts I can help with.

**Pull request closed without merging**
