### PR TITLE
Added missing translation for user_block_profile

### PR DESCRIPTION
**Pull request by tskorupka**

### CODE REVIEW

**Comment by core23** [comment]
Can you please squash your commits?

**Comment by tskorupka** [comment]
Sorry, I think I'm newbie how to do it?

**Comment by core23** [comment]
https://github.com/sonata-project/SonataAdminBundle/blob/master/CONTRIBUTING.md#squash-your-commits

**Comment by core23** [comment]
Thank you @tskorupka

**Comment by tskorupka** [comment]
Thank you @core23 too :)

**Pull request merged**
