### PR TITLE
Added ManagerInterface to UserManager

### PR DESCRIPTION
**Pull request by core23**
Maybe we should add the ``ManagerInterface`` to the ``UserManagerInterface`` and ``GroupManagerInterface`` with the next major release.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Can you please explain why?

**Comment by core23** [comment]
Because all methods from the ``ManagerInterface`` were implemented and refered to a ``@inheritdoc`` which does not exist at the moment.

**Comment by Soullivaneuh** [comment]
Sounds good. @rande what do you think?

**Comment by core23** [comment]
ping @rande

**Comment by OskarStark** [comment]
:+1:

**Comment by OskarStark** [comment]
Thank you @core23

**Pull request merged**
