### PR TITLE
Set google authenticator and controllers as an optional dependency

### PR DESCRIPTION
**Pull request by hason**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Please rebase your PR.

**Comment by Soullivaneuh** [comment]
> theses dependancies are required for the api

What do you means?

**Comment by sagikazarmark** [comment]
Duplicate of #653

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
