### PR TITLE
Security token can be null in login form on 404

### PR DESCRIPTION
**Pull request by core23**
Rebase of https://github.com/sonata-project/SonataUserBundle/pull/613

### Changelog

```markdown
### Fixed
- Fixed a potential null error in `SecurityFOSUser1Controller::loginAction`

```

### Subject
The security token could be null while you're trying to login.

### CODE REVIEW

**Comment by OskarStark** [comment]
Really a `NullPointerException` ?

**Comment by greg0ire** [comment]
> Really a NullPointerException ?

@core23 java background is real ;)

**Comment by core23** [comment]
Changed the Changelog message ;)

**Comment by OskarStark** [comment]
> Changed the Changelog message ;)

Thank you @core23 , this looks good to me 👍

**Pull request merged**
