### PR TITLE
Merge 3.x on add_support_for_fos_user2

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targetting this branch, because I am crazy (and I am trying to merge 3.x on this branch.

## Subject

Trying to do a merge on add_support_for_fos_user2 of 3.x. I am not sure if it will work or not. This is for science

### CODE REVIEW

**Comment by greg0ire** [comment]
Strange… no Travis…

**Comment by jordisala1991** [comment]
Travis:

**Comment by greg0ire** [comment]
Explanation : https://github.com/sonata-project/SonataUserBundle/blob/3.x/.travis.yml#L6

**Comment by greg0ire** [comment]
So… YOLO merge?

**Comment by jordisala1991** [comment]
Wait

**Comment by jordisala1991** [comment]
Go travis, our hopes are with you...

**Comment by greg0ire** [comment]
Good luck!

**Comment by greg0ire** [comment]
we believe in you

**Comment by greg0ire** [comment]
ezgif-3-538627ac6e

**Comment by jordisala1991** [comment]
It does not make sense to merge 3.x as is, because FOSUser 2.0 is not compatible with PHP 5.3 and SF 2.3.

So I did change a little travis.yml and composer.json to match requirements of master

**Comment by jordisala1991** [comment]
Well, the build is green now, but not sure, we will have to test this on a project first?

**Comment by greg0ire** [comment]
I don't know who uses that…

**Comment by jordisala1991** [comment]
I am trying on one project...

this is the error I am getting:

```
[RuntimeException]
  An error occurred when executing the "'assets:install --symlink --relative '\''web'\'''" command:
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Symfony\Component\Security\Core\Authentication\Provider\
  DaoAuthenticationProvider::__construct() must be an instance of Symfony\Component\Security\Core\User\UserProviderInterface, instance of Sonata\UserBundle\Entity\UserManage
  r given, called in /home/ubuntu/cache/dev/appDevDebugProjectContainer.php on line 7343 in /home/ubuntu/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentic
  ation/Provider/DaoAuthenticationProvider.php:43
  Stack trace:
  #0 /home/ubuntu/cache/dev/appDevDebugProjectContainer.php(7343): Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider->__construct(Object(Sona
  ta\UserBundle\Entity\UserManager), Object(Symfony\Component\Security\Core\User\UserChecker), 'main', Object(Symfony\Component\Security\Core\Encoder\EncoderFactory), true)
  #1 /home/ubuntu/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(314): appDevDebugProjectContain in /home/ubuntu/vendor/symfony/symfony/src/S
  ymfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php on line 43
```

**Comment by jordisala1991** [comment]
It is working. I need some reviews / tests. @sonata-project/contributors help :)

I prepared a branch on my test project: https://github.com/jordisala1991/ArchetypeSonata/tree/feature/fos_user . In case you don't want to setup everything.

This PR does not need to be perfect, we can improve this branch on another ones (just to avoid all this commit madness), but if everything works, would be better.

Once this branch works perfectly, I can do a PR against master to move all we need.

**Comment by jordisala1991** [comment]
Fixed password resetting.

**Comment by greg0ire** [comment]
YOLO let's merge!

**Comment by jordisala1991** [comment]
It works like a charm, you will see

**Comment by magedan** [comment]
I was trying to use this branch, but was stucked with the following error:

>  [Symfony\Component\DependencyInjection\Exception\ScopeWideningInjectionException]
>  Scope Widening Injection detected: The definition "sonata.user.registration.form.handler.default" references the service "request" which belongs to a narrower scope. Generally, it is safer to either move "sonata.user.registration.form.handler.default" to scope "request" or alternatively rely on the provider pattern by injecting the container itself, and requesting the service "request" each time it is needed. In rare, special cases however that might not be necessary, then you can set the reference to strict=false to get rid of this error.

I looked further and found that this service, declared in `form.xml`, seems like not used anymore:

``` xml
<service id="sonata.user.registration.form.handler.default" class="Sonata\UserBundle\Form\Handler\RegistrationFormHandler" public="false">
    <argument type="service" id="sonata.user.registration.form"/>
    <argument type="service" id="request"/>
    <argument type="service" id="fos_user.user_manager"/>
    <argument type="service" id="fos_user.mailer"/>
    <argument type="service" id="fos_user.util.token_generator"/>
</service>
```

because FOSUserBundle doesn't have `FOS\UserBundle\Form\Handler\RegistrationFormHandler` class.

I'm not sure if it must be removed or not.

Anyway, thanks a lot for your contribution!

**Comment by jordisala1991** [comment]
Are you using registration of users?

**Comment by jordisala1991** [comment]
I am planning on a refactor of the code, this first PR was just for getting ir merged with 3.x and start working on it.

For me it is working with the normal usage: login, logout, edit profile, reset password.

**Comment by magedan** [comment]
Well, I use "standard" user registration provided by the FOSUserBundle on frontend without any custom form handlers.
I got this error while executing `composer update`, not during registration process.
Btw, if that makes sense, Symfony version is 2.8.18

**Pull request merged**
