### PR TITLE
Indention

### PR DESCRIPTION
**Pull request by OskarStark**
I am targeting this branch, because this is a doc fix.

### CODE REVIEW

**Comment by jlamur** [comment]
Isn't it called *indentation* in english? https://en.wikipedia.org/wiki/Indentation_(typesetting)

**Comment by Soullivaneuh** [comment]
@jlamur You are correct. The commit message may be fixed while merging.

**Comment by greg0ire** [comment]
@jlamur @Soullivaneuh Both work

**Comment by greg0ire** [comment]
And I usually use "indention", I believe it is more widely used.

**Pull request merged**
