### PR TITLE
Travis and composer improve

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Travis: Based on sonata-project/SonataAdminBundle#3033.

Composer: Setup default minimum stability for a more clear configuration.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@rande some jobs has a memory limit error: https://travis-ci.org/sonata-project/SonataUserBundle/jobs/66164473

Any idea of why?

**Comment by rande** [comment]
@Soullivaneuh no but we can try to add a memory limit to -1

**Comment by Soullivaneuh** [comment]
Done. Hope it will help.

**Comment by Soullivaneuh** [comment]
@rande Made a mistake. You can stop this build: https://travis-ci.org/sonata-project/SonataUserBundle/builds/66193251

**Comment by Soullivaneuh** [comment]
@rande 

```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 64 bytes)
```

Well, Travis seems to not give a single f*ck of my env settings...

**Comment by Soullivaneuh** [comment]
Well, let's try with this one: https://github.com/travis-ci/travis-ci/issues/960#issuecomment-14506725

**Comment by Soullivaneuh** [comment]
fred-mercury-queen-meme-so-close

**Comment by Soullivaneuh** [comment]
@rande this job seems to be stuck: https://travis-ci.org/sonata-project/SonataUserBundle/jobs/66197064

Can you please restart it?

**Comment by Soullivaneuh** [comment]
Well, compose get stuck on `--prefer-lowest` tag.

I opened an issue some times ago about it: https://github.com/composer/composer/issues/3993

It is not made by the `composer.json` update. I just ran the same command on master, same result.

@rande I think the best is to add this job on `allowed_failure` and wait for a composer fix.

I'll create an issue on this repository to remember it.

**Pull request merged**
