### PR TITLE
BugFix of mongoDb support

### PR DESCRIPTION
**Pull request by Dropaq**
It's a fix of severe bug.

Support of mongoDB by Sonata-User-Bundle was completely broken, because Doctrine was unable to find `FOS\UserBundle\Resources\config\doctrine\User.mongodb.xml` while it iterates through inheritance.

So basically **FOSUserBundle** has `FOS\Model` which is extended twice by `FOS\Entity` and by `FOS\Document`.

At the same time **SonataUserBundle** implementing similar logic, but `Sonata\UserBundle\Model\User` is extending `FOS\Entity`.
It really doesn't make any sense. The only reason of existence of this Model is preventing from copy-pasting common fields between Entity and Document, but the price of it is too high.

Since support of PHP 5.3 is necessary and usage of traits is impossible, I just copied methods from Entity into Document.
Also I've fixed logic of `UserManagerInterface` and `UserManagerProxy` which caused similar problem with serializer. So basically missed declaration of service for mongoDB resulted in Fatal Error on project update.
By now all methods of newly updated `UserManagerInterface` for `Document\UserManager` is replaced with stubs throwing an Exception. I suppose serialization wouldn't work for mongo, but looks like everything else is up an running.

### CODE REVIEW

**Comment by OskarStark** [comment]
@Dropaq would you like to rebase your PR and check if it works?

**Comment by Dropaq** [comment]
@OskarStark Yep, sure, I can try. The only conflicting changes I see so far were introduced in this commit: d7e776e70292ff7f48f6ff2d32099818ef7760eb Shouldn't be hard to reflect them in my PR.

**Comment by OskarStark** [comment]
Thank you @Dropaq

**Comment by Dropaq** [comment]
@OskarStark done;
PR is rebased, and all tests are passing.

**Comment by OskarStark** [comment]
ping @rande

**Comment by Dropaq** [comment]
@OskarStark @rande guys?

**Comment by Dropaq** [comment]
@SonataCI done

**Comment by greg0ire** [comment]
Can you please apply this fix : https://styleci.io/analyses/8jlVM7

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
