### PR TITLE
Replaced all instances of "admin_pool" with the global "sonata_adminPool"

### PR DESCRIPTION
**Pull request by mweimerskirch**
Related to https://github.com/sonata-project/SonataAdminBundle/pull/3464

### CODE REVIEW

**Comment by rande** [comment]
Not sure we can merge this PR for now. As this bundle can be used with previous version on the AdminBundle

**Comment by mweimerskirch** [comment]
I see. For the use-case I described (being able to more easily integrate external components with the admin bundle by being able to use the same template) it is not required, so I think you could just tag this PR for the next major release.

**Comment by OskarStark** [comment]
ok i schedule this PR for 3.0, but for this release it is RTM for me :+1:

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
