### PR TITLE
Adding support for php version 8

### PR DESCRIPTION
**Pull request by 4c0n**
## Subject

Adding support for PHP version 8.0.
I am targeting this branch, because I need the current version to support PHP 8.

### CODE REVIEW

**Comment by 4c0n** [comment]
@phansys Saw you were involved in the last releases, not sure if you are the maintainer, but would you mind taking a look at this?
I cannot imagine that the builds are failing because of the php version constraint change in the composer.json file btw.

**Comment by VincentLanglet** [comment]
@4c0n You should rebase your branch

**Comment by 4c0n** [comment]
@VincentLanglet There the branch is updated and the checks pass now. :)

**Comment by VincentLanglet** [comment]
Thanks ! In order to be sure that the php8 build pass, can you update the test.yaml in the same way than https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1285

Also a PR on dev-kit will be needed similar to https://github.com/sonata-project/dev-kit/pull/1428. 
It will save me time if you want to create it :)

**Comment by 4c0n** [comment]
@VincentLanglet Created the PR on the dev-kit repo:
https://github.com/sonata-project/dev-kit/pull/1497

**Comment by 4c0n** [comment]
@VincentLanglet The change you requested for the github action is already there it seems :smile: https://github.com/4c0n/SonataUserBundle/blob/d061474db869de35b4343fa61074fc676257b61f/.github/workflows/test.yaml#L66

**Comment by VincentLanglet** [comment]
> @VincentLanglet The change you requested for the github action is already there it seems 😄 https://github.com/4c0n/SonataUserBundle/blob/d061474db869de35b4343fa61074fc676257b61f/.github/workflows/test.yaml#L66

Check again my link.
You need to remove the code 
```
- name: Configuration required for PHP 8.0
              if: matrix.php-version == '8.0'
              run: composer config platform.php 7.4.99
```
And move the php8 version to the required check :)

**Comment by 4c0n** [comment]
@VincentLanglet Thanks, I got a little confused, it's modified now.

**Comment by 4c0n** [comment]
I see it's failing now because of the friendsofsymfony/user-bundle. I'll go chase my other PR first:
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/3001

**Comment by phansys** [comment]
@4c0n, I forced the pipeline execution.
As you can see, we have a problem supporting PHP 8 because the dependency with "friendsofsymfony/user-bundle".

**Comment by VincentLanglet** [comment]
> @4c0n, I forced the pipeline execution.
> As you can see, we have a problem supporting PHP 8 because the dependency with "friendsofsymfony/user-bundle".

There are PR for this:
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/3001
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/3003

But there is not a lot of activity on this bundle. The only/best way to add php8 support is to drop FOSUserBundle.

**Pull request closed without merging**
