### PR TITLE
use range in composer.json instead of ~

### PR DESCRIPTION
**Pull request by OskarStark**
### Subject

The build was failing, due to a new composer lint check

### Example

https://travis-ci.org/sonata-project/SonataUserBundle/jobs/134360668

### CODE REVIEW

**Comment by greg0ire** [comment]
The commit message says you're using a new syntax, but the diff shows you also allow ~0.11 and ~0.12, with no explanation. Is it a mistake or not? Please make it clear.

**Comment by OskarStark** [comment]
updated @greg0ire

**Comment by greg0ire** [comment]
I don't still get why you suddenly allow 0.11 and 0.12. This is what you need to clarify.

**Comment by OskarStark** [comment]
> I don't still get why you suddenly allow 0.11 and 0.12. This is what you need to clarify.

damn you are totally right here... i mixed things up with the other PR, will fix it in a minute

**Comment by greg0ire** [comment]
Looks good @OskarStark :)

**Comment by OskarStark** [comment]
ping @Soullivaneuh is this correct in this case?

**Comment by Soullivaneuh** [comment]
> ping @Soullivaneuh is this correct in this case?

:+1:

**Comment by greg0ire** [comment]
Thanks @OskarStark !

**Comment by OskarStark** [comment]
patch or not @Soullivaneuh ?

**Comment by Soullivaneuh** [comment]
@OskarStark Normaly `pedantic` but this label will be set this night only. So patch for the moment,

**Pull request merged**
