### PR TITLE
Make REST dependency optional

### PR DESCRIPTION
**Pull request by core23**

### CODE REVIEW

**Comment by OskarStark** [comment]
pleas eadd some info in the documentation

**Comment by core23** [comment]
done @OskarStark

**Comment by OskarStark** [comment]
Thank you @core23

**Comment by pepeh** [comment]
@OskarStark 
After this commit bundle don't working.

[Doctrine\Common\Annotations\AnnotationException]
[Semantical Error] The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc" in method Sonata\UserBundle\Controller\Api\GroupController::getGroupsAction() does not exist
  , or could not be auto-loaded.

**Comment by pepeh** [comment]
@core23 After this commit bundle don't working.

**Comment by OskarStark** [comment]
@core23 can you please check this?

**Comment by core23** [comment]
Do you have some customization or extensions on the UserBundle? By default the ``Sonata\UserBundle\Controller\Api\GroupController`` isn't loaded by the UserBundle.

With this commit the dependencies of ``friendsofsymfony/rest-bundle`` and ``nelmio/api-doc-bundle`` are optional and not autoloaded by composer. Please have a look at the ``installation.rst``.

**Comment by pepeh** [comment]
@core23, I have installed friendsofsymfony/rest-bundle without nelmio/api-doc-bundle

**Pull request merged**
