### PR TITLE
Mark some services public

### PR DESCRIPTION
**Pull request by OskarStark**
I am targeting this branch, because this is BC.

## Changelog

```markdown
### Fixed
- The following services can be get via the container again:
  `sonata.user.user_manager`
  `sonata.user.group_manager`
  `Sonata\UserBundle\Form\Type\RolesMatrixType`
  `Sonata\UserBundle\Entity\UserManagerProxy` 
```

please use merge commit

### CODE REVIEW

**Comment by OskarStark** [comment]
> Please write a changelog directed at end users.
done @greg0ire

**Comment by kunicmarko20** [comment]
Still failing @OskarStark

**Comment by OskarStark** [comment]
Tests still fail, but I don't get why same PHP version with 3.4 works fine 🤔 

any idea @sonata-project/contributors ?

**Comment by kunicmarko20** [comment]
setAlias was returning void in the older version, that is probably the issue.

**Comment by kunicmarko20** [comment]
Yep, just found it:

3.3 https://github.com/symfony/dependency-injection/blob/3.3/ContainerBuilder.php#L794
3.4 https://github.com/symfony/dependency-injection/blob/3.4/ContainerBuilder.php#L855

**Comment by OskarStark** [comment]
let's try again

**Comment by kunicmarko20** [comment]
Just fix lint and we can merge it.

**Comment by OskarStark** [comment]
done @kunicmarko20

**Comment by kunicmarko20** [comment]
Thank you @OskarStark !

**Pull request merged**
