### PR TITLE
"top" and "bottom" blocks in SonataUserBundle dashboard

### PR DESCRIPTION
**Pull request by stphnpt**
Allows for "top" and "bottom" blocks (with "col-lg-12" block class) in user dashboard (Profile/show) the same way it is handled in admin dashboard (Core/dashboard)

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Could you please:

* Explain a little bit your PR with some example
* Add related tests
* Fix CS: https://travis-ci.org/sonata-project/SonataUserBundle/jobs/76410499

**Comment by stphnpt** [comment]
- Currently, you can only define "right", "left" and "center" for block positions in the user dashboard config file (sonata_user.yml), whereas in the admin dashboard (sonata_admin.yml) you have "right", "left", "center", "top" and "bottom" (to have header and footer blocks in addition to multi-columns blocks) ... I just apply what is currently done in SonataAdminBundle (dashboardAction in CoreController and Core/dashboard template) in SonataUserBundle (showAction in ProfileFOSUser1Controller and Profile/show template), makes sense to me, no ?

- There is currently no test existing in SonataUserBundle for this feature... I'm unable to complement

- Sorry, but I don't understand the reason behind the Travis Ci fail.

**Comment by Soullivaneuh** [comment]
> Currently, you can only define "right", "left" and "center" for block positions in the user dashboard config file (sonata_user.yml), whereas in the admin dashboard (sonata_admin.yml) you have "right", "left", "center", "top" and "bottom"

Maybe. But this should be added on `sonata.user.configuration.profile_blocks` parameter, not on code.

> There is currently no test existing in SonataUserBundle for this feature... I'm unable to complement

Well, if you want, you can create one. :+1: 

> Sorry, but I don't understand the reason behind the Travis Ci fail.

I said it before: Coding standard are wrong. Use `make cs` command to fix it or do it manually.

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
