### PR TITLE
updates dutch translations

### PR DESCRIPTION
**Pull request by zghosts**
Updates Dutch translations

I am targeting this branch, because it updates the dutch translations

## Changelog

```markdown
### Changed
- Updates dutch translations
```

### CODE REVIEW

**Review by franmomu — DISMISSED** [review]

**Comment by VincentLanglet** [comment]
Can you rebase ? @zghosts

**Comment by zghosts** [comment]
rebase done

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks @zghosts

**Pull request merged**
