### PR TITLE
wip: ACE's losing after change username MASTER

### PR DESCRIPTION
**Pull request by mba242**
I am targetting this branch, because there is a old bugfix in symfony itselfs.
https://github.com/symfony/symfony/pull/8650

Related Bugs:
https://github.com/symfony/symfony/issues/5787
https://github.com/FriendsOfSymfony/FOSUserBundle/issues/505

Also its uses UserManager instead ModelManager to have upwards compatibility if UserManager implements/triggers new stuff.

## Changelog

Preserves ACE's if username changes.
Delete ACE's on user delete event.

Uses UserManager instead ModelManager in UserAdmin.

```markdown
### Added
- Sonata\UserBundle\Admin\Model::update($object)
    uses now getUserManager() instead  getModelManager()
    updates ACE's with Symfony\Component\Security\Acl\Dbal\MutableAclProvider

- Sonata\UserBundle\Admin\Model::delete($object)
    uses now getUserManager() instead  getModelManager()
    remove ACE's with Symfony\Component\Security\Acl\Dbal\MutableAclProvider

- Sonata\UserBundle\Admin\Model::getAccess()
    drops batchDelete-Action because 
        Sonata\AdminBundle\Controller\CrudController::batchActionDelete()
        uses ModelManager for deleting.
        ModelManager or UserManager dont care about ACE's.

- Sonata\UserBundle\Admin\Model::getAccess()
    drops (batch)delete-Action because 
        Sonata\AdminBundle\Controller\CrudController::batchActionDelete()
        uses ModelManager for deleting.
        ModelManager or UserManager dont care about ACE's.

### Removed
- Sonata\UserBundle\Admin\Model::preUpdate()
    updateCanonicalFields() && updatePassword() will triggered in UserManager

### Fixed
 User loses ACE's (Entity ownership) during change of username
### Security
 Other User can get ownership of entities.
```
### Steps to reproduce:
 - create user with username "boringUsername".
 - create some new entities with this user and check their ACE's - user should be owner.
 - rename username to "coolUsername"
 - look again to his ACE's he isn't anymore owner.
 - create other use with username "boringUsername"
 - look to enties the 1. user had  created - new user is now owner

 There is a simular behaver with deleting user.

## To do

- [ ] Find a better way for batch deleting users. 
       Perhaps CRUDController should iterate items and give to admin-class?
- [ ] Check BC, because UserManager::updateUser() returns void.
- [ ] Check Frontend, there should be same behavior. I didnt use it.

### CODE REVIEW

**Comment by greg0ire** [comment]
Please link your magnalist.com email address to your account, GH can't figure out who authored your commits otherwise

**Comment by greg0ire** [comment]
Uuuuh… you made all the files in the project executable…

**Comment by mba242** [comment]
whats this i had only changed one file

**Comment by greg0ire** [comment]
> I am targetting this branch, because there is a old bugfix in symfony itselfs.
symfony/symfony#8650

So? How does this imply making a BC-break?

**Comment by greg0ire** [comment]
I moved the steps to reproduce out of the changelog. The changelog is directed at end users of the package, not at developers, so you're not supposed to talk about internal things there.

**Comment by mba242** [comment]
the break makes abstractadmin::update();
        $result = $this->getModelManager()->update($object);
        // BC compatibility
        if (null !== $result) {
            $object = $result;
        }
dont know why - but userManager returns void

**Comment by greg0ire** [comment]
Either you plan to make this BC, and if yes you should target the stable branch, or you have a good reason not to and you should target master. If you're not sure yet to manage to make it BC or not, the stable branch might be the best choice anyway.

**Comment by mba242** [comment]
Dont know how to do it - stable is ok.

**Comment by greg0ire** [comment]
1. name your branch something else than `master` : `git checkout -b what_this_is_about`
2. rebase it on 3.x : `git rebase --interactive 3.x` (remove all the lines but the last one, which should show your commit
3. push that and create a new PR.

**Comment by mba242** [comment]
can we close it - i will do again -- also change my mail-address of repos

**Comment by mba242** [comment]
can you shredder the emailadress more, please?

**Comment by greg0ire** [comment]
Uuuuh… what do you mean by that?

**Comment by mba242** [comment]
https://github.com/sonata-project/SonataUserBundle/pull/808#issuecomment-264460895

its not my private adress

**Comment by greg0ire** [comment]
Ok it's not your private address, that's great… what am I supposed to do?

**Comment by mba242** [comment]
more unreadable, please.

**Comment by greg0ire** [comment]
Oooh ok… but that's no email address that's just a domain. but ok.

**Comment by greg0ire** [comment]
Done

**Comment by mba242** [comment]
gracias

**Comment by greg0ire** [comment]
De nada

**Pull request closed without merging**
