### PR TITLE
Update version number for admin bundle

### PR DESCRIPTION
**Pull request by dragosprotung**
Version 2.4 does not exist anymore.
See https://github.com/sonata-project/SonataAdminBundle/issues/3731 for details.

### CODE REVIEW

**Comment by OskarStark** [comment]
@Soullivaneuh can you please have a look?

**Comment by Soullivaneuh** [comment]
3.0 bundles are WIP. You can follow work here: https://github.com/sonata-project/SonataAdminBundle/issues/3731

Sonata user it's a bit more complex than user. I'll have to work on it with @th3mouk and @rande.

If you want to get it working this, use aliases on you composer.json like described here: https://github.com/sonata-project/SonataAdminBundle/issues/3731#issuecomment-212636270

Closing this one.

**Comment by dragosprotung** [comment]
@Soullivaneuh The only reason for this PR is because 2.4 does not exist anymore in the admin bundle, so composer will fail to install the user bundle even if i do not use the admin bundle

**Comment by Soullivaneuh** [comment]
@dragosprotung You can use composer alias waiting for the fix: https://getcomposer.org/doc/articles/aliases.md#require-inline-alias

**Comment by sagikazarmark** [comment]
I am not entirely sure about the validity of the reasoning, given that using `~3.0@dev` is valid in other packages?

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/composer.json#L28

Not complaining, I am perfectly fine with aliasing.

**Comment by Soullivaneuh** [comment]
@sagikazarmark This is WIP and sonata-user is a bit more complicated because of FOSUser 2.0 WIP too.

We will look at this ASAP.

**Comment by sagikazarmark** [comment]
Understood.

**Pull request closed without merging**
