### PR TITLE
[FOS2] Add support for fos user2

### PR DESCRIPTION
**Pull request by moux2003**
I've done the work of reporting some commits from master branch and fixing dependancies among sonata and fosuser's bundles.
This merge could save some people time for a new project as we wait for a stable release of fosUser 2

### CODE REVIEW

**Comment by OskarStark** [comment]
Ping @rande

**Comment by Bukashk0zzz** [comment]
@moux2003 Thanks. You save time for me)

**Comment by Soullivaneuh** [comment]
This branch has to be review before merge for new releases for two reasons.

* SF 2.3 support drop should not be here, because it's always supported by FOSUser 2.x
* The best would be to have BC between FOSUser 1 and 2 to push it on a new minor. In any case, no version should be release, especially major until FOSUser 2 get a stable release.

**Comment by Soullivaneuh** [comment]
Pless see https://github.com/sonata-project/SonataUserBundle/issues/730

**Comment by core23** [comment]
Please reabse @moux2003

**Comment by greg0ire** [comment]
Ask for help if you need some

**Comment by moux2003** [comment]
Ok I think I have applied last changes with success, not familiar with styleci but it seems to be conflicting with existing php cs conf file about arrays..

**Comment by greg0ire** [comment]
You have to do the following

1. fetch changes `git fetch --all`
2. `git rebase $name_of_the_remote_for_the_name_repo/add_support_for_fos_user2`
3. `git push --force`

You can see the remotes you have configured by typing `git remote -vvv`

**Pull request closed without merging**
