### PR TITLE
added sidebar group icon

### PR DESCRIPTION
**Pull request by net02**
because why not?

groupicon

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Could you rebase your PR?

And add before/after comparison screenshots please.

**Comment by OskarStark** [comment]
:+1:

**Comment by net02** [comment]
Rebased and squashed.. but it looks like i messed up at some point :|

**Comment by Soullivaneuh** [comment]
@net02 Well indeed, you f*ck up this PR. :-)

Which commands did you use for your rebase?

**Comment by Soullivaneuh** [comment]
Please read this: http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

You can use `fixup` instead of `squash` too.

**Comment by net02** [comment]
Well looks like the rebase was fine, but pulling & merging origin instead of forcing push wasn't really smart on my side!

**Comment by Soullivaneuh** [comment]
Sound better. :-)

> And add before/after comparison screenshots please.

Could you please do that?

**Comment by net02** [comment]
Before
vs
After

(took some time since I hadn't got a spare project with the updated UI yet)

**Comment by OskarStark** [comment]
:+1:

**Comment by Soullivaneuh** [comment]
Nice work, thanks!

**Pull request merged**
