### PR TITLE
Manual merge

### PR DESCRIPTION
**Pull request by greg0ire**
cc @vyshkant

### CODE REVIEW

**Comment by vyshkant** [comment]
@greg0ire I think you made a mistake while merging thees branches: I can't see the modification of `composer.json` I'd made (I'd changed the version of "matthiasnoback/symfony-dependency-injection-test" to "^2.2")

I think it could help.

**Comment by greg0ire** [comment]
@vyshkant oh right! This does not play well with the other mnoback dependency sadly. Can you have a look?

**Comment by greg0ire** [comment]
Here is how to get my code: 

```
git checkout -b greg0ire-master master
git pull https://github.com/greg0ire/SonataUserBundle.git master
```

**Comment by vyshkant** [comment]
I think the problem is that the `matthiasnoback/SymfonyConfigTest` does not support PHPUnit 5.7.

https://github.com/matthiasnoback/SymfonyConfigTest/blob/e1539aa8552126b9ce41852ab23957a2315f1709/composer.json#L19-L21

And the `matthiasnoback/SymfonyDependencyInjectionTest` too.

https://github.com/matthiasnoback/SymfonyDependencyInjectionTest/blob/434ed11fd16b90b2432954c777d6162690a8048c/composer.json#L22-L24

So if to be consistent, we must either refuse to use the `matthiasnoback/*`, or switch to a PHPUnit 6.

**Comment by vyshkant** [comment]
Or we can continue to use older versions, in which case I need to rewrite the tests.

**Comment by greg0ire** [comment]
I'd rather you use that last solution, switching to phpunit 6 is not something we can do at the very short term I think.

**Comment by vyshkant** [comment]
@greg0ire Where should I commit my changes?

**Comment by greg0ire** [comment]
on the stable branch, let's keep the difference minimal please.

**Comment by vyshkant** [comment]
> on the stable branch, let's keep the difference minimal please.

See #929

**Comment by greg0ire** [comment]
Wow @core23 you're an early bird!

**Pull request merged**
