### PR TITLE
asset return "/" if default avatar is empty

### PR DESCRIPTION
**Pull request by jbinfo**
I am targetting this branch, because fix a bug.

## Changelog

```markdown
### Fixed
- `asset` return `/` if default avatar is empty
```

## Subject

`asset` return `/` if default avatar is empty

### CODE REVIEW

**Comment by greg0ire** [comment]
Hi and thanks for your contribution!

Why did you remove the PR template?

**Comment by jbinfo** [comment]
@greg0ire Just doing it rapidly. Do you want to create new one ?

**Comment by greg0ire** [comment]
No, just edit it.

**Comment by jbinfo** [comment]
Done, thank you.

**Pull request merged**
