### PR TITLE
Small pr for making templates to be overridable

### PR DESCRIPTION
**Pull request by aLkRicha**
I am targeting this branch, because it's small improvement.

## Changelog

```markdown
### Fixed
- templates paths
```

- before: SonataUserBundle:Admin:Security/Resetting/request.html.twig
- after: @SonataUser/Admin/Security/Resetting/request.html.twig

### CODE REVIEW

**Comment by greg0ire** [comment]
Thanks @AlKricha!

**Comment by jordisala1991** [comment]
Too late but the changelog and the commit message should explain what you did here

**Comment by greg0ire** [comment]
I squashed with a sane commit message

**Comment by jordisala1991** [comment]
I upgraded the changelog message with your commit message :P

**Comment by greg0ire** [comment]
Thanks, I did this from my phone

**Pull request merged**
