### PR TITLE
Renamed two german strings

### PR DESCRIPTION
**Pull request by OskarStark**
and removed a blank line

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I'm not speaking german. :-)

But can you please explain why your translation would be better?

Thanks.

**Comment by OskarStark** [comment]
of course :)

ist some kind of double...

i'll try to explain it with english by side:

```Benutzerregistrierung``` in english is ```User registration```, but this is shorter:
```Registrierung``` - ```Registration```

so i stripped the ```Benutzer``` (```User```) of the translations, to make it shorter.

**Comment by Soullivaneuh** [comment]
I see.

I'm ok for `title_user_registration` but I would like to keep `title_user_account` as is because it's the same way as the english translation: https://github.com/sonata-project/SonataUserBundle/blob/master/Resources/translations/SonataUserBundle.en.xliff#L11

A I right? If yes, could you please update it?

**Comment by OskarStark** [comment]
@Soullivaneuh can you please merge, i reverted the change

**Comment by Soullivaneuh** [comment]
Could you please squash your commits?

**Comment by OskarStark** [comment]
@Soullivaneuh done

**Comment by Soullivaneuh** [comment]
Thanks!

**Comment by OskarStark** [comment]
np

thank you!

**Pull request merged**
