### PR TITLE
Farsi translation added for FOSUserBundle

### PR DESCRIPTION
**Pull request by saeedasalisaf**
Farsi translation added for FOSUserBundle

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please Squash your commits into one?

**Comment by OskarStark** [comment]
ping @saeedasalisaf

**Comment by saeedasalisaf** [comment]
Sorry for late answer. Squashed.

**Comment by OskarStark** [comment]
Hey @saeedasalisaf looks like it didn't work, there are still 3 commits

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
