### PR TITLE
Deprecate ReST API

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Deprecated
- Deprecated ReST API with FOSRest, Nelmio Api Docs and JMS Serializer.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Same was applied for other bundles. Once merged, merged to 5.x and removed deprecated messages, we can deprecate DatagridBundle safely.

**Comment by wbloszyk** [comment]
Can you add upgrade note? https://github.com/sonata-project/SonataPageBundle/pull/1365/files#diff-c698cbb1f2afce655c27e32ebfc8d9f37af04b8164a1d8d609da71d2858c6697

And also be consider and add `NEXT_MAJOR` to whole `@deprecated`.

**Review by wbloszyk — COMMENTED** [review]
Can you add upgrade note? https://github.com/sonata-project/SonataPageBundle/pull/1365/files#diff-c698cbb1f2afce655c27e32ebfc8d9f37af04b8164a1d8d609da71d2858c6697

And also be consider and add `NEXT_MAJOR` to whole `@deprecated`.

**Comment by jordisala1991** [comment]
> Can you add upgrade note? https://github.com/sonata-project/SonataPageBundle/pull/1365/files#diff-c698cbb1f2afce655c27e32ebfc8d9f37af04b8164a1d8d609da71d2858c6697
> 
> And also be consider and add `NEXT_MAJOR` to whole `@deprecated`.

Done, Added upgrade note and added more next major comments.

**Review by wbloszyk — APPROVED** [review]

**Review by VincentLanglet — CHANGES_REQUESTED** [review]
We need to add NEXT_MAJOR to removeable PageableInterface in 
https://github.com/sonata-project/SonataUserBundle/blob/8885f677e0dfde1e02d88f3ec0b48c2dd8dfa8c5/src/Model/UserManagerInterface.php
https://github.com/sonata-project/SonataUserBundle/blob/8885f677e0dfde1e02d88f3ec0b48c2dd8dfa8c5/src/Model/GroupManagerInterface.php

And need to deprecate and add a NEXT_MAJOR for `getPager` method
https://github.com/sonata-project/SonataUserBundle/blob/8885f677e0dfde1e02d88f3ec0b48c2dd8dfa8c5/src/Entity/UserManager.php#L119
https://github.com/sonata-project/SonataUserBundle/blob/8885f677e0dfde1e02d88f3ec0b48c2dd8dfa8c5/src/Entity/GroupManager.php#L37
https://github.com/sonata-project/SonataUserBundle/blob/8885f677e0dfde1e02d88f3ec0b48c2dd8dfa8c5/src/Document/UserManager.php#L36
https://github.com/sonata-project/SonataUserBundle/blob/8885f677e0dfde1e02d88f3ec0b48c2dd8dfa8c5/src/Document/GroupManager.php#L36

This allow to remove the datagridBundle dependency

**Comment by VincentLanglet** [comment]
This PR will allow to close https://github.com/sonata-project/dev-kit/issues/1465 :)

**Comment by jordisala1991** [comment]
I already added all deprecations, can you point where it is missing? Both entity folder and model folder are already done.

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
> I already added all deprecations, can you point where it is missing? Both entity folder and model folder are already done.

Sorry, I need glasses.

**Comment by jordisala1991** [comment]
I will try the merge and the code removal later

**Pull request merged**
