### PR TITLE
Custom type extensions

### PR DESCRIPTION
**Pull request by sagikazarmark**
Contains a possible fix for sonata-project/SonataCoreBundle#217

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Ping @rande @Soullivaneuh @OskarStark

**Comment by sagikazarmark** [comment]
Closing as already fixed.

**Comment by rande** [comment]
@sagikazarmark sorry didn't see this PR ...

**Comment by sagikazarmark** [comment]
No problem, yours was better anyway, it followed the conventions.

**Pull request closed without merging**
