### PR TITLE
Allow "friendsofsymfony/rest-bundle:^3.0"

### PR DESCRIPTION
**Pull request by phansys**
## Subject

Allow "friendsofsymfony/rest-bundle:^3.0".

I am targeting this branch, because these changes respect BC.

## Changelog

```markdown
### Added
- Added support for "friendsofsymfony/rest-bundle:^3.0";
- Added public alias `Sonata\UserBundle\Controller\Api\UserController` for `sonata.user.controller.api.user` service;
- Added public alias `Sonata\UserBundle\Controller\Api\GroupController` for `sonata.user.controller.api.group` service.
### Removed
- Removed support for symfony/*:<4.4;
- Removed support for deprecated "rest" routing type.
```
Sonata\UserBundle\Controller\Api\GroupController

## To do

- [x] Update the tests;
- [x] Update the docs;
- [x] Update the routing in order to use other route type than "rest".

### CODE REVIEW

**Comment by phansys** [comment]
I'd like to check the former API routing implementation, but I couldn't because the XSD schema validation for the "rest" routing type is not working:
```
[ERROR 1845] Element '{http://friendsofsymfony.github.com/schema/rest}routes': No matching global declaration available for the validation root.
```

**Comment by wbloszyk** [comment]
@phansys This RP will fix API working for each sonata bundles in sandbox. Mybe we can add support for NelmioApiDocBundle ^3.0 or even ^4.0? Current 2.x is not maintained anymore. It must be upgrade to allow support Symfony5 to dev. Can you create dev-kit issue with TODO list? 

BTW, I can help with it. Just give me example ir tell what to do.

**Comment by phansys** [comment]
>@phansys This RP will fix API working for each sonata bundles in sandbox. Maybe we can add support for NelmioApiDocBundle ^3.0 or even ^4.0? Current 2.x is not maintained anymore. It must be upgrade to allow support Symfony5 to dev. Can you create dev-kit issue with TODO list?

Sure @wbloszyk, Thank you!
Nevertheless, I'd prefer to merge this PR first, since it is blocking third party projects to use "friendsofsymfony/rest-bundle:^3.0", while that's not the case with "nelmio/api-doc-bundle".
I'll try to add support for version "nelmio/api-doc-bundle:^3.0" in other PR.
IMO, support for version 4 must wait because it's using OAS 3.0, so that will be a BC break.
Based on how easy can be that change, I'll open a TODO list at dev-kit if I need help.
Do you agree?

**Comment by wbloszyk** [comment]
You can also create simmilar to my issue: https://github.com/sonata-project/dev-kit/issues/697
- Step 1 - add support for friendsofsymfony/rest-bundle
- Step 2 - add suport for nelmio/api-doc-bundle
...

This will show for everyone about this feature and how far you are.

**Comment by greg0ire** [comment]
Thanks @phansys !

**Pull request merged**
