### PR TITLE
[2.2] Replaced routing deprecated arguments

### PR DESCRIPTION
**Pull request by phansys**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

Replaces arguments that are deprecated from Symfony 2.2:

Before:
```xml
<route id="fos_user_resetting_reset" pattern="/reset/{token}">
    <default key="_controller">SonataUserBundle:ResettingFOSUser1:reset</default>
    <requirement key="_method">GET|POST</requirement>
</route>
```

After:
```xml
<route id="fos_user_resetting_reset" path="/reset/{token}" methods="GET POST">
    <default key="_controller">SonataUserBundle:ResettingFOSUser1:reset</default>
</route>
```

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@phansys could you please rebase your PR?

**Comment by phansys** [comment]
I didn't see anything to rebase @Soullivaneuh. Please notice that this PR was done against 2.2, and the [parent commit of this PR](https://github.com/phansys/SonataUserBundle/commit/42b22e7626eaf6d68e14b4e2da7a871b21e228a2) is the same as the [current HEAD of 2.2](https://github.com/sonata-project/SonataUserBundle/commit/9716d46303706f0f00ad1931a436bdd085cc978b).

**Comment by Soullivaneuh** [comment]
Didn't notice that.

Could you please propose this PR on `master` then?

We don't accept PR on another branches for the moment.

Thanks.

**Comment by phansys** [comment]
Closing in favor of #570.

**Pull request closed without merging**
