### PR TITLE
Manual merge

### PR DESCRIPTION
**Pull request by jordisala1991**

### CODE REVIEW

**Comment by jordisala1991** [comment]
I think there were some previous manual merge that went wrong, because I had to fix some composer.json lines

**Comment by jordisala1991** [comment]
and test on SonataAdminExtension

**Comment by greg0ire** [comment]
> I think there were some previous manual merge that went wrong, because I had to fix some composer.json lines

The last one was performed by CI, that's weird… what was wrong in `composer.json`?

**Comment by jordisala1991** [comment]
This PR changed the composer.json but was not changed on master: https://github.com/sonata-project/SonataUserBundle/pull/1132

It is a bit old so multiple manual merges has been applied

**Pull request merged**
