### PR TITLE
Moved method definition to interface

### PR DESCRIPTION
**Pull request by core23**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Which interface you mean? Lot of modified methods does not have parents.

And please use `{@inheritdoc}` instead of `@inheritdoc`

**Comment by core23** [comment]
Some methods are only defined in the concrete user class, would be better to move them to the interface. 

What do you mean with "Lot of modified methods does not have parents"?

**Comment by core23** [comment]
@Soullivaneuh ping

**Comment by Soullivaneuh** [comment]
> What do you mean with "Lot of modified methods does not have parents"?

Nothing. My IDE just drank wine.

But, adding method to interface is BC break.

If this could not be handled, this should be merge only on next major release.

BTW, an upgrade note should be inserted.

**Comment by core23** [comment]
Changelog should be fine now

**Pull request closed without merging**
