### PR TITLE
Add functional tests

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this branch is being reworked to work without FOSUser and it needs some basic coverage for main features.

Those test were possible thanks to @Runroom and https://github.com/Runroom/RunroomUserBundle (were I copied and adapted most of this code)

Mention to @aerrasti and @DaniCristante for the help developing the original tests :)

### CODE REVIEW

**Review by VincentLanglet — DISMISSED** [review]

**Comment by VincentLanglet** [comment]
Can't this test be added like this in 4.x ?

**Comment by jordisala1991** [comment]
Let me try a rebase

**Comment by jordisala1991** [comment]
s

**Comment by jordisala1991** [comment]
We might need a tool to be able to rollback transactions on database, something like: 

https://github.com/dmaicher/doctrine-test-bundle

**Comment by jordisala1991** [comment]
It does not work with 4.x, and I don't know why...

**Comment by jordisala1991** [comment]
Nope, test cannot be move like this between branches. It needs further refactor / more changes.

**Comment by jordisala1991** [comment]
Will need: https://github.com/sonata-project/dev-kit/pull/1814

**Comment by jordisala1991** [comment]
With this we will have a nice coverage for all the main features of this bundle:
- Login/Logout
- Admin pages (edit, list, create)
- Reset password (complete flow)

**Review by VincentLanglet — DISMISSED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Pull request merged**
