### PR TITLE
DevKit updates for master branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by OskarStark** [comment]
@greg0ire rebase is needed

**Comment by greg0ire** [comment]
@OskarStark : conflict resolution will do :P

**Comment by OskarStark** [comment]
Travis failed :(

**Comment by greg0ire** [comment]
[This commit](https://github.com/sonata-project/SonataCoreBundle/pull/293/commits/e22941d1f097dfc68aef53427ccbd72e39e7703c) seems to be needed.

**Comment by jordisala1991** [comment]
This is blocked until we merge 3.x on master (I think it will be manual merge)

**Pull request merged**
