### PR TITLE
Require sphinx 1.8.5

### PR DESCRIPTION
**Pull request by greg0ire**
## Subject

2.0.0 seems to break our build, see https://github.com/fabpot/sphinx-php/issues/46

I am targeting this branch, because this is BC.

### CODE REVIEW

**Comment by greg0ire** [comment]
Maybe yes... Is the contents of the file the same for all repos?

**Comment by jordisala1991** [comment]
https://github.com/sonata-project/dev-kit/blob/master/project/docs/requirements.txt

**Comment by greg0ire** [comment]
Great news! I'll make a PR, this one will serve as a proof.

**Comment by jordisala1991** [comment]
This is not needed anymore, right?

**Pull request closed without merging**
