### PR TITLE
Better route name for sonata admin security

### PR DESCRIPTION
**Pull request by sagikazarmark**
I didn't find any reference to this route name, so I don't think it is actually a BC break.

### CODE REVIEW

**Comment by OskarStark** [comment]
ah sorry, didn't catch that this was a doc change... my fault :)

**Comment by sagikazarmark** [comment]
No problem. :+1:

**Comment by sagikazarmark** [comment]
I still don't get why a simple doc change makes the tests failing. I guess there is something with the tests.

**Comment by OskarStark** [comment]
Thank you @sagikazarmark

**Pull request merged**
