### PR TITLE
Removed useless ROLE_SUPER_ADMIN check in UserAdmin

### PR DESCRIPTION
**Pull request by core23**
You can't edit the groups or status of other ROLE_SUPER_ADMIN users.

Refs https://github.com/sonata-project/SonataUserBundle/issues/706

### CODE REVIEW

**Comment by OskarStark** [comment]
what about $this->isGranted('ROLE_SUPER_ADMIN') ??

**Comment by greg0ire** [comment]
@OskarStark see #706

**Comment by OskarStark** [comment]
ping @core23

**Comment by core23** [comment]
> what about `$this->isGranted('ROLE_SUPER_ADMIN')` ??

What do you mean by that? IMO we don't need a permission check here, because this would prevent admins to modify security informations in some cases.

**Comment by OskarStark** [comment]
👍

**Pull request merged**
