### PR TITLE
Travis: Only run supported php versions

### PR DESCRIPTION
**Pull request by core23**
Drop support for outdated php versions: https://secure.php.net/supported-versions.php

### CODE REVIEW

**Comment by core23** [comment]
@rande Should we add php >=5.5 as a composer dependency?

**Comment by OskarStark** [comment]
what about keeping the travis stuff, allow failures on outdated versions and add 5.5. to composer.json ?

**Comment by core23** [comment]
Good idea @OskarStark 
Moved the PHP 5.3 and 5.4 stuff to the allow failure section.

**Comment by OskarStark** [comment]
Thank you @core23

**Pull request merged**
