### PR TITLE
DevKit updates for 4.x branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by jordisala1991** [comment]
Lets remove this PR and wait for dev kit to open it again (it would be nice if dev kit could auto rebase or reapply changes)

**Comment by VincentLanglet** [comment]
> Lets remove this PR and wait for dev kit to open it again (it would be nice if dev kit could auto rebase or reapply changes)

It would be nice if dev-kit could delete the branch after the merge. :p

**Comment by jordisala1991** [comment]
> > Lets remove this PR and wait for dev kit to open it again (it would be nice if dev kit could auto rebase or reapply changes)
> 
> 
> 
> It would be nice if dev-kit could delete the branch after the merge. :p 

hmm, It already does that 🤔

**Comment by VincentLanglet** [comment]
Since I'm getting this notification
image

I thought it was you

**Comment by jordisala1991** [comment]
When I merge this Pr it auto deletes the branch, but when dev kit merges it, the branch gets deleted too

**Pull request closed without merging**
