### PR TITLE
Redirect to admin dashboard if already logged in

### LINKED ISSUE #619: Admin login bad redirection for already logged in user
When a user is already logged in and goes to `/admin/login` it should redirect to the dashboard. Instead it redirects to the profile page which is not just illogical (since you want to go to the dashboard), but also bad: in case frontend login is not allowed, it ends up with an error saying route `sonata_user_profile_show` cannot be found (in case frontend routes are not set).

### PR DESCRIPTION
**Pull request by sagikazarmark**
Fix #619

### CODE REVIEW

**Comment by OskarStark** [comment]
Thank you @sagikazarmark

**Comment by OskarStark** [comment]
yes it is @sagikazarmark but in the current master, not in the ``2.2``

@Soullivaneuh what do you think, can we cherry pick this commit and backport it to 2.2 and the create a release?

**Comment by aderuwe** [comment]
@sagikazarmark @OskarStark thanks for passing this on, hope it's possible!

**Comment by OskarStark** [comment]
@aderuwe could you please open a new issue, so that this need keep to stay in focus?

that would be awesome

**Comment by aderuwe** [comment]
@OskarStark done!

**Pull request merged**
